name: CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.0", "3.1", ruby-head, jruby-head]

    steps:
    - uses: actions/checkout@v2
    - name: Install cURL Headers
      run: sudo apt-get install libcurl4-openssl-dev
    - name: Remove Gemfile.lock
      run: |
        rm Gemfile.lock
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # 'bundle install' and cache gems
        ruby-version: ${{ matrix.ruby }}
    - name: Run tests
      run: bundle exec rake test
